apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voltes
  template:
    metadata:
      labels:
        app: voltes
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-files
        configMap:
          name: voltes-html
