apiVersion: v1
kind: Service
metadata:
  name: voltes-service
spec:
  selector:
    app: voltes  # Update this to match the pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Ensure this matches the port your app is listening on
  type: LoadBalancer
